Fluffy-Frontier/FluffySTG

code/__DEFINES/traits.dm
code/modules/surgery/organs/tongue.dm
modular_skyrat/modules/customization/modules/client/augment/organs.dm
tgstation.dme
~ff/modules/autoaccent/code/autoaccent.dm

Авто-акцент для фелинидов, таяр, вульп и всех тех, кто использует кошачий/собачий биологический язык.
Добавляет автоматический акцент, привязанный к типу языка для котоподобных и собакоподобных существ. Через verb во вкладке IC можно отключить эту фичу.
<details>
<summary>Примеры: </summary>
Фелинид мурчит с включеным авто-акцентом
Фелинид мурчит с выключеным авто-акцентом
Вульпа рычит с включенным авто-акцентом
Вульпа рычит с выключенным авто-акцентом
Языки в меню настройки персонажа
</details>
:cl:
add: added auto-accent for vulpkanins, tajarans and felinids and anthromorphs.
qol: any auto-accent can be disabled with IC -> Toggle auto-accent.
/:cl:

Auto accent

---

modular_skyrat/modules/microfusion/code/microfusion_cell.dm
modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
tgstation.dme

Данный ПР восстанавливает "валидное" и пригодное состояние МКРов, позволяя перезаряжать их.
МКР больше не будут игрушкой которая валяется в арсенале до момента тотальной прокачки или покупки речарджер аттачмента.
<details>
</details>
:cl:
balance: MCR now can be reloaded normally again!
/:cl:

MCR nerf revert

---

code/modules/admin/admin_verbs.dm
code/modules/admin/topic.dm

Данный ПР сделает доступным для использования несколько кнопок для тех, у кого нет +SERVER флага. Изменённые кнопки:
- Задержка начала раунда.
- Ручной конец раунда.
- Смена карты.
- Изменение времени полёта эвакуационного шаттла.
Ивентологам будет проще проводить некоторые вещи.
<details>
</details>
:cl:
qol: Eventmakers now able to change map, delay round start, manualy end rounds and change shuttle arrival time!
/:cl:

[NON-MODULAR] EVENTMAKER QOL

---

modular_skyrat/modules/pollution/code/pollution.dm

More instance of pollution polluting runtime logs.
The `pollution` var is found only on `turf/open` but for some reason the for loop was iterating over 'anything' in `atmos_adjecent_turfs`, which can be `turf/closed` etc. Changed it to use the inbuilt for loop typechecking so that doesn't happen.
Fixes that.
<details>
<summary> There were 100's of these.</summary>
</details>
Nothing player facing

[Skyrat Mirror] [MODULAR] Fixes some pollution runtime spam

---

_maps/map_files/debug/runtimestation.dmm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24400
Original PR: https://github.com/tgstation/tgstation/pull/79039
adds like two human spawner wands to runtimestation
its more convenient than spawning humans or a wand for it when you need to test with more than 3 dummies
runtimestation is not playerfacing

[TG Mirror] literally just maps in human spawner wands to runtimestation [MDB IGNORE]

---

modular_skyrat/modules/modular_implants/code/nifsofts/soulcatcher.dm
modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm

Race condition. In the parent `/datum/nifsoft/New()` it calls `update_theme()` which expects the `linked_soulcatcher` var to be set, but it doesn't get set until the end of `/datum/nifsoft/soulcatcher/New()`. So it runtimes.
This fixes that.
Also fixes a bonus runtime:
Less runtiming is good
<details>
</details>
Nothing really significantly player facing I don't think?

[Skyrat Mirror] [MODULAR] Fixes a nif related runtime with update_theme

---

code/_onclick/other_mobs.dm
code/datums/mutations/hulk.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/living_defense.dm
code/modules/surgery/organs/internal/cyberimp/augments_arms.dm
code/modules/unit_tests/combat.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24401
Original PR: https://github.com/tgstation/tgstation/pull/79033
Fixes #79031 
Fixes #79042
I forgot some logic here when making the human override. 
Not the cleanest way to do it but it'll suffice. 
:cl:  Melbert
fix: You can punch yourself again
/:cl:

[TG Mirror] Fixes being able to punch yourself [MDB IGNORE]

---

modular_skyrat/modules/contractor/code/datums/midround/outfit.dm
modular_skyrat/modules/skyrat-uplinks/code/uplink_implant.dm
tgstation.dme

This PR does exactly what it says on the tin. Technically, it deletes the 13tc subtype and resets contractors back to the 0tc version of the implant, but that's all backend - what **YOU**, dear reader, are reading this pr body for, is plain and clear. It does everything it says it does. One telecrystal? Nah. Three? Hell no. Twelve? Not even close. Zero! They get none. I don't know who thought giving them some was a great idea. Those angels are gone, holmes. Away. Dusted. Why?
The contractor OPFOR kit and /tg/ balanced - yes, /tg/ balanced - traitor kit do not offer a 13tc discount. This is a full set of gear that would cost a traitor 20tc to get half of, and yet, you START with thirteen telecrystals. Thirteen! That's enough for a .357 magnum revolver. That's enough for sleeping carp. …

[Skyrat Mirror] [MODULAR] Removes the 13 telecrystals contractors start with

---

code/modules/hydroponics/grown.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24409
Original PR: https://github.com/tgstation/tgstation/pull/79045
The recent changes to the food defines have broken the quality scaling for the fruit wine. This PR fixes the regression.
Bug fix
:cl: MTandi
fix: Distilled drink quality is fixed - can't give a mood debuff anymore
/:cl:

[TG Mirror] Distillation fixed [MDB IGNORE]

---

code/modules/experisci/experiment/types/scanning_fish.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24408
Original PR: https://github.com/tgstation/tgstation/pull/79030
I've forgot that, for some reasons, both experiments and experiment handlers have an experiment(or) whitelist var.
This will fix #78921
:cl: Ghommie
fix: Fish analyzers can now be actually used for experiments.
/:cl:

[TG Mirror] [NO GBP] fish analyzers can now be actually used for experiments. [MDB IGNORE]

---

code/modules/mob/living/basic/jungle/venus_human_trap.dm
code/modules/mob/living/simple_animal/hostile/alien.dm
code/modules/mob/living/simple_animal/hostile/constructs/wraith.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
code/modules/mob/living/simple_animal/hostile/megafauna/_megafauna.dm
code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
code/modules/mob/living/simple_animal/hostile/mimic.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
code/modules/mob/living/simple_animal/hostile/ooze.dm
code/modules/mob/living/simple_animal/hostile/zombie.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24402
Original PR: https://github.com/tgstation/tgstation/pull/79037
CI started spamming with runtimes. 
`AttackingTarget()` wasn't passing the `target` as an arg. Fixes that. Also added the arg in a bunch of its overrides because they were not there. I know we're phasing out simple mobs but in the meantime broken things bad.
Fixes bug
:cl: vinylspiders
fix: fixed runtime caused by simple mobs AttackingTarget() missing an arg
/:cl:

[TG Mirror] Fixes CI failure from AttackingTarget not passing the attacked_target in its args [MDB IGNORE]

---

code/game/objects/structures/spirit_board.dm
code/modules/mob/living/basic/space_fauna/revenant/_revenant.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24403
Original PR: https://github.com/tgstation/tgstation/pull/79029
Allows Revenants to use Ouija boards. 
Cleans up some code of Ouija boards in general.
Default Ouija boards now have some more options to select. 
Admins can now VV Ouija board options. 
Adds a 1% chance for a Ouija board to be called Luigi board.  
Revenants being excluded from spirit board fun is kinda messed up, even though they're telepaths. 
:cl:  Melbert
add: Revenants can now use Ouija Boards
add: Ouija Boards now have more options to select from by default (and admins can VV it to even more options) 
fix: Blind people are now worse at using Ouija Boards
/:cl:

[TG Mirror] Revenants can use spirit boards [MDB IGNORE]

---

code/datums/components/scope.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24404
Original PR: https://github.com/tgstation/tgstation/pull/78941
If you ghost while mid-scope (or similarly, if you get dusted/your mob gets deleted) the mob's cursor would get all messed up due to some oversights. This just clears up some of these logic errors and ensures everything gets cleaned up properly.
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/24189
Fixes https://github.com/tgstation/tgstation/issues/78756
Fixes a bug. I don't think scopes are even in use here but they are downstream.
<details>
<summary>Deleted and being dusted resets perspective and cursor properly</summary>
</details>
<details>
<summary>So does ghosting</summary>
</details>
:cl: vinylspiders
fix: being killed or …

[TG Mirror] Fixes a bug with the scope getting stuck on mobs that get dusted or ghost [MDB IGNORE]

---

code/__HELPERS/priority_announce.dm
code/controllers/subsystem/shuttle.dm
tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
tgui/packages/tgui-panel/styles/tgchat/chat-light.scss

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24413
Original PR: https://github.com/tgstation/tgstation/pull/79052
I forgot light mode exists half way through making PR https://github.com/tgstation/tgstation/pull/78995, apparently. Also fixes the weird spacing on shuttle evac calls and dark mode alert text, reduces the padding on either side of announcements.
:cl:  LT3
spellcheck: More announcement CSS fixes, now including light mode
/:cl:

[TG Mirror] Announcement CSS hotfix [NO GBP] [MDB IGNORE]

---

code/game/machinery/computer/accounting.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24412
Original PR: https://github.com/tgstation/tgstation/pull/79048
It's possible to have bank accounts created with `null` jobs. This results in a runtime  bluescreen that breaks the account management console for the whole round. 
<details><summary>Not ideal</summary>
</details>
The runtime comes from trying to access `title` from the null job datum in `ui_data()` which results in the ui data not being sent.
https://github.com/tgstation/tgstation/blob/c10bf15c4a9b71eec325ea2f201a68defb80943b/code/game/machinery/computer/accounting.dm#L22-L29
---
This PR just guards against that. Similar patterns can be seen everywhere else where this data is accessed.
<details><summary> For example</summary> …

[TG Mirror] Fixes source of tgui errors in accounts console [MDB IGNORE]

---

code/modules/fishing/fishing_minigame.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24411
Original PR: https://github.com/tgstation/tgstation/pull/79050
What it says on the tin. Runtime shown above, it was missing the user arg.
Bugfix
:cl: vinylspiders
fix: "line snapped" and "rod dropped" balloon alerts will now display when they are supposed to while fishing
/:cl:

[TG Mirror] Fixes a fishing balloon alert runtime [MDB IGNORE]

---

_maps/templates/lazy_templates/wizard_den.dmm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24373
Original PR: https://github.com/tgstation/tgstation/pull/78723
I am the mapping demon, the mapping vampire, the mapping LICH. I am going to suck the soul out of every single map in the game. I've sucked the beach away mission's soul now I'm going for the wizard's den.
The wizard's den no longer looks like a giant flying cucumber, also it looks a lot better and has a lot better themeing. The wizard also has a book directing them to their wiki page to help them.
:cl:  Fazzie
add: The wizard's den now has a book with the guide to wizard. Hope that helps their winrate!
qol: The wizard's den no longer looks like a flying cucumber and has received a major overhaul. Hooray!
/:cl:

[TG Mirror] Updates the wizard's den [MDB IGNORE]

---

_maps/RandomRuins/IceRuins/skyrat/icemoon_underground_syndicate_base1_skyrat.dmm
_maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm
modular_skyrat/modules/mapping/code/lavaland_ruin_code.dm

miners now spawn with a point card in their otherwise underfilled backpack
medical areas now have a sansufentanyl crate next to the blood freezer
mining cards: point transfer good
medical sansufentanyl: trade goods for potential HMS sufferers
<details>
</details>
:cl: Hatterhat
qol: Interdyne miners now spawn with a point transfer card in their backpacks.
qol: Sansufentanyl now spawns in the Interdyne base, since it's something they make in-lore. It can be found in a freezer crate next to their blood freezer.
/:cl:

[Skyrat Mirror] interdyne - gives miners point cards, places sansufentanyl in the medical area

---

_maps/map_files/Birdshot/birdshot.dmm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24418
Original PR: https://github.com/tgstation/tgstation/pull/79056
Fixes #79003
I've added a couple of useful tools to Birdshot's ordnance lab - a second RPD, and two holofan projectors. 
I also removed one (1) cable from under the reinforced window by ordnance's front door. I didn't touch the other electrified windows in the science wing.
The extra RPD lets two people comfortably work in ordnance, like they can on most maps, and the holofan projectors allow changes to be made to the burn or freeze chambers without disaster. Most other maps have these things available, so it seems reasonable to add them here.
As pointed out in #79003, a quick toxins moment is all it takes for the modified window to …

[TG Mirror] Birdshot ordnance QoL 

---

code/modules/bitrunning/objects/netpod.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24417
Original PR: https://github.com/tgstation/tgstation/pull/79053
Clicking an active bitrunner pod as an observer will allow you to orbit that bitrunning pod's current avatar.
Makes it easier to check up on what those cheeky Bitrunners are up to!
:cl:  Rhials
qol: As an observer, clicking on a bitrunning pod will let you orbit it's bitrunning avatar. Cool!
/:cl:

[TG Mirror] Clicking a bitrunning pod orbits its avatar 

---

code/modules/power/apc/apc_attack.dm
code/modules/power/apc/apc_main.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24427
Original PR: https://github.com/tgstation/tgstation/pull/79077
Someone implemented `Exited` but didn't remove this code, it's not necessary and all it does is runtime now.

[TG Mirror] Fix APC cell removal runtime 

---

code/datums/status_effects/debuffs/debuffs.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24428
Original PR: https://github.com/tgstation/tgstation/pull/79065
Fixes #77333 
Spasms don't trigger if you are incapacitated (including in stasis), your hands are blocked, or you are immobilized. 
Consistency. Mutations and brain traumas don't fire on-life due to stasis (which are both how you acquire spasms). Otherwise it shouldn't bother triggering if you can't actually... spasm at the moment. 
:cl:  Melbert
fix: Spasms won't trigger in stasis, incapacitated, if your hands are blocked, or you are immobilized. 
/:cl:

[TG Mirror] Spasms don't trigger in stasis or otherwise 

---

code/modules/mob/living/ventcrawling.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24429
Original PR: https://github.com/tgstation/tgstation/pull/79027
May or may not close https://github.com/tgstation/tgstation/issues/79018
Basically we slept during the `do_after()` and the vent may have been welded while we were sleeping, meaning we could "phase through a welded vent". Just a silly hole in ventcrawling logic that we should be accounting for.
I think there's a few issues with ventcrawling (i.e. it being traitbased and not something like an element) but we can tackle that later. Let's just fix any potential holes and issues that might come with it.
:cl: san7890
fix: People should be crawling into welded vents a lot less now.
/:cl:
No guarantee on the linked issue disappearing since I …

[TG Mirror] Fixes hole in ventcrawl logic 

---

tff_modular/master_files/code/modules/job/job_blacklist.dm

Обновляет запреты на работки для ГБСов и тешарь. Полный список указать сложно, просто... гляньте в игре потом, хз
Наверное невозможность зайти на охранника карго за тешарю или ГБСа - это хорошо
<details>
гбс
фаст тешарбы
</details>
:cl:
balance: locked several jobs for GAS and fast tesharies
code: sorted job blacklist file so it can be easier to find required job datums
/:cl:

Обновляет список запрещённых для (новых) тешарь и ГБСов работ

---

code/game/objects/structures/mirror.dm
code/modules/mob/living/basic/space_fauna/robot_customer.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24426
Original PR: https://github.com/tgstation/tgstation/pull/79072
`ADD_TRAIT` doesn't take a list
:cl:  Melbert
fix: Magic Mirrors properly prevent you from being soft locked
fix: Robo customers are as robust as before
/:cl:

[TG Mirror] Fixes two improper calls to ADD_TRAIT (magic mirror, robo customer)  

---

code/__DEFINES/~skyrat_defines/loadouts.dm
modular_skyrat/modules/loadouts/loadout_items/_loadout_datum.dm
modular_skyrat/modules/loadouts/loadout_items/loadout_datum_toys.dm
modular_skyrat/modules/loadouts/loadout_ui/loadout_manager.dm

You can now rename and describe any loadout item, not just plushies.
Lets players customize their clothing and stuff more. Fun flavor!
https://github.com/Skyrat-SS13/Skyrat-tg/assets/4081722/94d50a00-8352-47d2-94b4-411df58cb5bb
:cl: Iamgoofball
qol: You can now rename and describe any loadout item, not just plushies.
/:cl:

[Skyrat Mirror] [MODULAR] You can now rename and describe any loadout item, not just plushies.

---

code/game/objects/items/robot/robot_parts.dm
code/game/objects/items/robot/robot_upgrades.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/silicon/robot/robot_defense.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24431
Original PR: https://github.com/tgstation/tgstation/pull/79047
The boris module that turns a cyborg into an AI shell is a bit weird. It can be used like an MMI or a positronic brain directly on a completed borg exoskeleton. It can also be used like any other cyborg upgrade on a completed cyborg, if an only if that cyborg is not controlled by a player already. If you reset an AI shell, it is intended to make the cyborg un-player controlled and to drop the boris module onto the ground. From there, you are supposed to be able put it back in like any other upgrade.
However, this behavior was bugged. Due to certain parts of the code not calling procs they should have, the boris module was not being …

[TG Mirror] B.O.R.I.S. Module Bugfix 

---

code/datums/dna.dm
code/game/objects/structures/mirror.dm
modular_skyrat/modules/customization/datums/dna.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24425
Original PR: https://github.com/tgstation/tgstation/pull/79075
Not sure why this exactly was happening but I just changed around some vars and it fixed
Also it was assigning a qdeling datum to a mob. Bad bad bad
:cl:  Melbert
fix: Magic Mirrors can change your race again (?)
/:cl:

[TG Mirror] Fixes magic mirrors not being able to change your race (?) 

---

code/__DEFINES/dcs/signals/signals_storage.dm
code/datums/components/bloody_spreader.dm
code/datums/materials/meat.dm
code/datums/storage/storage.dm
code/game/objects/items/food/meatslab.dm
code/game/objects/items/storage/backpack.dm
code/modules/antagonists/fugitive/hunters/hunter_gear.dm
code/modules/antagonists/heretic/items/heretic_blades.dm
code/modules/mapfluff/ruins/spaceruin_code/meateor.dm
code/modules/mob/living/basic/space_fauna/meteor_heart/meteor_heart.dm
tgstation.dme

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24436
Original PR: https://github.com/tgstation/tgstation/pull/78743
Adds 'Bloody Spreader' component that bloodies everything it touches!
For example inserting an item into it if it is a storage item. Or entering it if it's a turf, or bumping onto it, or... you get the point, hopefully.
Added this component to the MEAT backpack, meat slabs, bouncy castles, meateor fluff, meateor heart, and the heretic sanguine blade. 
Gave most of these the blood walk component as well, which spreads blood if it's dragged around.
Meat slabs contain a limited amount of both components, eventually they will 'dry out'.
Meat isn't meaty and squelchy enough, this will make it meatier. It also makes the janitor suffer.
:cl: …

[TG Mirror] Adds 'Bloody Spreader' component that bloodies everything it touches 

---

code/_onclick/hud/rendering/render_plate.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24438
Original PR: https://github.com/tgstation/tgstation/pull/79062
Adds a color matrix to the game plate on halloween that greyscales slightly and dims/drops dim colors for a harsher dropoff
I'm not sure the dropoff is strong enough, can't decide.
:cl: LemonInTheDark
add: Screen is now more grungy for halloween
/:cl:

[TG Mirror] Tints the screen for halloween 

---

code/modules/mob/living/carbon/carbon_defense.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24442
Original PR: https://github.com/tgstation/tgstation/pull/79036
be it far from me to explain why the args not getting put in directly broke this, but reinserting them into the check_passout stuff from #78657 fixes it.
should close #79034 but I have no clue if other similar changes to how args were being handled might not have problems elsewhere.
atmospheric simulator, breathing mechanics good, also chems and i guess bleeding and whatnot
:cl: Higgin
fix: automatic breathers rejoice. oxyloss now knocks people out again.
/:cl:

[TG Mirror] fixes oxyloss not knocking people out at 50 

---

code/game/objects/structures/beds_chairs/bed.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24437
Original PR: https://github.com/tgstation/tgstation/pull/79057
Update the overlay if the brakes are on at mapload
:cl:  LT3
fix: Maploaded medical beds now have correct brake lights
/:cl:

[TG Mirror] Medical beds show correct overlay  

---

code/__HELPERS/dynamic_human_icon_gen.dm
code/modules/hallucination/mother.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24445
Original PR: https://github.com/tgstation/tgstation/pull/79098
Yep. So I was investigating why a player was weirdly unable to equip things, or do a lot of stuff. And encountered in the runtime logs that _their species datum was deleted_. How? Well...the answer is...your mother.
---
So the hallucination of 'your mother' uses the hallucinator's species datum to create itself here:
https://github.com/tgstation/tgstation/blob/07096ffcad0f06ac9276c38275fa4e09e7dece41/code/modules/hallucination/mother.dm#L80
Which then calls set_species, but it passes _your actual species datum in as an arg_
https://github.com/tgstation/tgstation/blob/07096ffcad0f06ac9276c38275fa4e09e7dece41/code/__HELPERS/dynamic_human_ …

 Fixes a bug where your mother would delete your species after calling you a disappointment, rendering you a broken husk of a mob 

---

code/modules/reagents/chemistry/recipes/medicine.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24443
Original PR: https://github.com/tgstation/tgstation/pull/78961
Modifies the amount of cellulose fibers needed to create an advanced regenerative mesh from 20u to 10u.
Currently, medicated sutures require 10u of cellulose fiber to create. This means they can be created directly from a (medium complexity) botany crossbreed, as the 5% cellulose fiber gene from tower caps can produce 10u cellulose fibers with the densified chemicals trait.
This change allows botanists to create a similar crossbreed which produces advanced regenerative meshes. Lavaland plants, mutations and crosspollination are still needed to complete this, so it's a similarly tough project to the existing suture plant.
:cl: Yttriums …

 Rebalances advanced regenerative mesh recipe 

---

code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/silicon/robot/robot.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24444
Original PR: https://github.com/tgstation/tgstation/pull/78816
it was screaming runtimes each time an ai disconnected or reconnected to an ai shell because it never unregistered the death disconnect signal properly.
```
[2023-10-01 14:56:38.191] RUNTIME: runtime error: living_death overridden. Use override = TRUE to suppress this warning.
- Target: Calaban Default Shell-980 (/mob/living/silicon/robot/shell) Proc: disconnect_shell (code/datums/signals.dm:39)
- proc name:  stack trace (/proc/_stack_trace)
-   source file: code/__HELPERS/stack_trace.dm,4
-   usr: Calaban (/mob/living/silicon/ai)
-   src: null
-   usr.loc: the floor (150,25,4) (/turf/open/floor/circuit)
-   call stack:
-  stack …
```

 Fixes ai shell deployment not unregistering a death signal properly 

---

code/modules/power/tesla/coil.dm
code/modules/power/tesla/energy_ball.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24447
Original PR: https://github.com/tgstation/tgstation/pull/79061
Fixes tesla coil zap cutoff being scaled high when it didn't need to. Tesla coil zaps didn't scale with the old power scaling before it got removed, so the tesla coil zaps got nerfed due to the scaling changes of zap effects. This PR does not fix the fact that tesla coil zaps will deal less damage though. An easy clean fix doesn't seem possible, and adding a damage multiplier is cringe.
For fixing tesla coil zap damage, the only reasonable solution seems to be to unscale almost every other zapper (the vast majority of them don't seem to be able to power the grid, so it doesn't matter), and then scaling zap damage scaling back up. I …

 Fix tesla coil zaps. 

---

code/datums/status_effects/debuffs/fire_stacks.dm
code/modules/religion/pyre_rites.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24446
Original PR: https://github.com/tgstation/tgstation/pull/79095
- Fixes #78881
Husks were having their firestacks decay too rapidly to allow chaplains to perform their burning sacrifice rite.  The decay rate is lowered and you can now sacrifice husked bodies (caused only by burns) for the pyre rite sacrifice.
Pyre sacrifice now is functional.
:cl: timothymtorres
fix: Fix husks fire decay rate to be slower. Pyre chaplains can now use husked bodies (only caused by burns) to complete their burning sacrifice rite.
/:cl:

  Fix husks fire decay to be slower and allow pyre rite to sacrifice husks 

---

modular_skyrat/modules/medical/code/wounds/synth/blunt/robotic_blunt_T3.dm
modular_skyrat/modules/medical/code/wounds/synth/blunt/secures_internals.dm

Title.
Blunt wounds now display the current step and specific treatment instructions on wound scans. Crowbarring open a T2/3 wound now warns you if it can shock you.
bugs bad and qol good
<details>
</details>
:cl: nikothedude
fix: Unlinked RCDs now function on T3 synth blunt wounds
qol: Synthetic blunt wounds now show their current step along with instructions on wound scans
qol: Synthetic blunt wounds now warn you if crowbarring open the limb can shock you
/:cl:

[MODULAR]  Improves the UX of synth wounds + fixes RCDs on collapsed superstructures

---

code/modules/mob/living/carbon/human/_species.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24452
Original PR: https://github.com/tgstation/tgstation/pull/79064
Species hard deletes are a little difficult to track down without the ref tracker due to having no owner so I figure this might help... just a tiny bit. Maybe. 
This will let us know if the species hard-deleting was applied to a human or not. `properly_gained` is set to `TRUE` in `on_species_gain`. If it is false, it might be a shadow species kept in DNA or some other weird place or something.

 Adds a smidge of information for species hard-dels 

---

modular_skyrat/modules/reagent_forging/code/forge_weapons.dm

adds the ability to transform arrows to different types by attacking them with the conversion item (bronze tile to bronze arrow, bone to bone arrow, and sinew to ash arrow).
I also removed the forged arrow subtype-- after some well needed qol PRs, they became unused and not necessary.
THIS DOES NOT REMOVE THE RECIPES-- there may be cases where you need to be able to craft them so I kept the recipes.
Rather than being stuck in the crafting menu, more item interactions like this keeps "immersion."
<details>
</details>
:cl: jjpark-kb
add: you can change arrows into different types by hitting them with the conversion item (bronze tile for bronze, bone for bone, and sinew for ash)
del: removes the forged arrow subtype
/:cl:

arrows can be converted

---

modular_skyrat/modules/ashwalkers/code/buildings/antfarm.dm

Ants were producing smelted/completed ores-- there was a comment about how "the ants have forges." This PR fixes that by making all the smelted/completed ores back to the unprocessed ores, as well as adding stone.
As much as I enjoy the thought of ants having their own forging setup, they probably should only be producing the raw materials so that the community members can actually do the work and smelt the ore!
<details>
</details>
:cl: jjpark-kb
fix: ant farms produce the unprocessed ore now instead of the smelted/completed ore
add: added stone to the ore list of ant farms
/:cl:

add stone to antfarm and remove smelted sheets

---

code/game/atoms.dm
code/game/objects/items/devices/radio/radio.dm
code/modules/reagents/reagent_containers/cups/drinks.dm
code/modules/reagents/reagent_containers/syringes.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24455
Original PR: https://github.com/tgstation/tgstation/pull/78719
Also optimizes the update_icon proc a little bit, especially as a round goes on, since everything is stored as an appearance (or text, gross) this allows us to only call on overlay update code if the managed overlays change.
This also fixes some sources of null overlays but it ended up being more things than I should shove into this pr if I were to fix all of them.
Should probably be testmerged for a little bit to make sure nothing weird comes from assuming everything being passed in has an appearance var.

 Fixes modified MA overlays potentially causing duplicate overlays 

---

code/modules/bitrunning/objects/netpod.dm
code/modules/bitrunning/server/obj_generation.dm
code/modules/bitrunning/virtual_domain/virtual_domain.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24459
Original PR: https://github.com/tgstation/tgstation/pull/78959
Adds two variables to bitrunner domains, one for making them not spawn disk items, and one for making them not grant disk abilities to bitrunner characters on loading into the domain.
Not presently used in any domains, but will be a mystery tool that will help us later.
I've thought of a few pretty good domains but the ideas behind them fall apart a bit of joey bitrunner can bring a desword and fireball into them.
:cl: Paxilmaniac
code: Bitrunner domains can now have spells or items from disks disabled if the domain maker wants such a thing
/:cl:

 Allows domains to forgo giving bitrunners their disk items and spells if that is desired 

---

code/datums/wires/explosive.dm
code/modules/mining/ores_coins.dm

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24457
Original PR: https://github.com/tgstation/tgstation/pull/79038
https://github.com/tgstation/tgstation/assets/70376633/8d15d7c9-51c2-4aeb-b1c6-4386168947da
i made it work slightly better too so
also this was in the code since like 2015 but it probably got broken sometime
also 10 second detonation timer is pretty harmless anyway so
bug bad
fyi this was added in 2015 https://github.com/tgstation/tgstation/pull/8587
:cl: mc-oofert
fix: making assembly activated bombs works again
/:cl:

 fixes gibtonite bomb 

---

code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
code/modules/antagonists/traitor/datum_traitor.dm
modular_skyrat/modules/Midroundtraitor/code/datum_traitor.dm
modular_skyrat/modules/Midroundtraitor/code/event.dm
tgui/packages/tgui/interfaces/TraitorObjectiveDebug.tsx
tgui/packages/tgui/interfaces/Uplink/ObjectiveMenu.tsx
tgui/packages/tgui/interfaces/Uplink/PrimaryObjectiveMenu.tsx
tgui/packages/tgui/interfaces/Uplink/calculateDangerLevel.tsx
tgui/packages/tgui/interfaces/Uplink/index.tsx

Mirrored on Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/24374
Original PR: https://github.com/tgstation/tgstation/pull/79020
Reputation has been renamed to 'Threat Level' to more accurately represent what it means.
Midround and latejoin traitors no longer have access to secondary objectives, the ones which give TC and objectives.
Midround antagonists, like traitor, shouldn't really have the progression system that is meant for roundstart. Final objectives in particular are only suited for traitors who have worked towards it from the start.
Reputation wasn't really a good name for the player-facing progression system of traitors as you'd passively gain progression which didn't make since if it was supposed to be your reputation.
:cl: Watermelon914
balance: …

 Removes progression from midround and latejoin traitor, renames reputation to threat level 

---

tff_modular/modules/custom_revolution/code/rev_head_role.dm
tff_modular/modules/custom_revolution/code/rev_team_role.dm

Лидер активистов больше не сможет спавнить брошюры будучи без сознания или мёртвым.
Меньше багов = хорошо
<details>
</details>
:cl:
fix: Leader activist no longer able to spawn brochures while being unconscious or dead.
/:cl:

Исправление бага c Активистами

---

modular_skyrat/modules/blueshield/code/blueshield.dm
modular_skyrat/modules/blueshield/code/closet.dm
tff_modular/modules/blueshield-rearm/code/weapon_beacon.dm
tgstation.dme

Переносит оружие БЩ в маяк для доставки, который позволяет БЩ выбрать оружие с которым он хочет быть.
Также код из этого ПРа может послужить основой для кастомных наборов снаряжения и для других ролей.
Сейчас у БЩ от крыс есть "подарок", а именно второе, лишнее оружие, которое спавнится у него в ящике. Просто так вырезать его - я счёл лишним (а также Крысы скоро вместо СМГ могут подарить ему эксклюзивную стреляблу), из-за чего я просто решил выдать Щиту девайс для доставки снаряжения, в котором он cможет выбрать желаемый ствол, так как не всем хочется играть с бластером и наоборот.
<details>
</details>
:cl:
qol: Blueshield's weaponry now can be picked by the player via delivery beacon.
/:cl:

Перемещение стартового оружия БЩ в маяк доставки с выбором снаряжения.

---

.github/workflows/auto_changelog.yml

NOVABOT_TOKEN -> SKYRATBOT_TOKEN
потому что к старому имени был привязан наш ключ)

Фиксим чейнджлоги

---

code/_onclick/click.dm
code/_onclick/cyborg.dm
code/_onclick/other_mobs.dm
code/modules/mob/living/basic/bots/cleanbot/cleanbot.dm
code/modules/mob/living/basic/guardian/guardian_types/explosive.dm
code/modules/mob/living/basic/guardian/guardian_types/gravitokinetic.dm
code/modules/mob/living/basic/pets/cat/cat.dm
code/modules/mob/living/simple_animal/bot/firebot.dm
code/modules/mob/living/simple_animal/bot/floorbot.dm
code/modules/mob/living/simple_animal/bot/mulebot.dm
code/modules/mob/living/simple_animal/bot/secbot.dm

Fixes #80566 
Fixes the wrong arguments being passed to
`COMSIG_LIVING_EARLY_UNARMED_ATTACK`.
It now properly receives the proximity flag. 
Changes clicking with handcuffs to no longer always assume no proximity.
Replaces some checks for hands blocked to some checks for `can_unarmed_attack` (which, currently, JUST checks for hands blocked, but this is good for future reasons, just in case)
:cl: Melbert
fix: Strong arm implant users can shove more correctly.  /:cl:

[MISSED MIRROR] Fixes `COMSIG_LIVING_EARLY_UNARMED_ATTACK` arguments (#80783)

---

code/modules/mob/living/carbon/human/_species.dm
code/modules/surgery/organs/internal/_internal_organ.dm

Adds a limit to burn damage that can be caused by freezing temperatures.
Fixes https://github.com/tgstation/tgstation/issues/80302
:cl: LT3
fix: Morgue trays and freezing temperatures will no longer husk bodies fix: Organs outside bodies will properly receive cold damage /:cl:

[MISSED MIRROR] Fixes morgue trays husking corpses, caps freezing burn damage (#80811)

---

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm
_maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm
modular_nova/modules/mapping/code/icemoon.dm
modular_nova/modules/mapping/code/lavaland.dm
tff_modular/modules/interdyne-remap/interdyne.dm
tgstation.dme

Я слегка модулязирол и обновил пути спавнеров.
Replaces Interdyne bases with a dome-like, Wavefield Science designed Interdyne laboratories. 
"Developed by Wavefield Science dome-like Interdyne laboratory that was dropped like a meteorite from space and deployed at crater created by landing impact.
An advanced laboratory itself fitted with a modular shield generator, defence perimeter turrets and external bridge."
It is actually the same interdyne we have now, but cozy and a much handier. 
I saw pr and some attempts to connect DS-2 with Interdyne via little ship, so i also built a landing zone for it at lavaland, if it will be needed someday, but.. im not pleased of DS-2 existance. Tired watching ds2 fullgeared admirals doing science here.
I playing mostly Interdyne so it's nice to …

[PORT] "Frozen Moonlight" Interdyne

---

tff_modular/modules/custom_revolution/code/rev_deconvert_machine.dm

Этот ПР добавит деконверт дефолтной ревы через ActiviZero2000
Увидел как в раунде спавнят дефолтную реву и ужаснулся тому, что единственная альтернатива майндшилду - это забивание головы ревера.
Я думаю, что нам стоит иметь альтернативный и более гуманный способ деконвертить обычную реву.
:cl:
add: Added new, more humane way to deconvert default revs via ActiviZero2000.
/:cl:

Default rev deconvertion feature

---

tff_modular/master_files/code/modules/job/job_trim.dm
tgstation.dme

Данный ПР добавит разрешение на оружие КМу, так как оно есть буквально у любой другой главы, в том числе СМО и СЕ.
Крысы (ныне Новы) выдали всем главам разрешение на оружие, но при этом забрав его у КМа. Причина почему КМ не получил лицензию на оружие - проста, карго по задумке нашего апстрима представляет независимую фракцию "ФТУ", у которой свои СОПы, регуляции и правила, не связанные с НТ, по этому ему не положена НТшная лицензия ведь разрешение на оружие у него есть в пределах территории ФТУ, которой является карго.
<details>
</details>
:cl:
add: Weapon permit for QM
/:cl:

Разрешение на оружие у КМа

---

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm
_maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm

Fixes machine frames for Interdyne, moves shuttle console vi indoors, expands perimeter fence, fixes some deco, some rrs.
Fixes are nice. 
:cl:
fix: fixed a few Dyne things
/:cl:

Dyne fixes3

---

tff_modular/modules/redsec/code/vending.dm
tff_modular/modules/redsec_reskins/code/redsec.dm

Мир намного ярче в гуччи - это факт.
Ну, епты бля, добавляет выбор между редсек и блюсек очками пискиперов в альтскинах оных, а также добавляет пискиперы в "ПРЕМИУМ ДЕЛЮКС ++ ПРИВАТНАЯ ГРУППА СОЧНЫЕ СЛИВЫ ДЕВОЧЕК ИЗ СБ" раздел вендомата.
Всё в этой игре решает не скилл и не манч, а твой дрип. Добавленные худы выглядят великолепно, а значит добавляют очки стиля, а значит на порядок увеличивают получаемое от игры удовольствие.
<details>
<summary>
Скриншоты
</summary>
</details>
:cl:
add: Added peacemaker glasses in the vending machines
add: Added reskins (choice between peacemaker and armadyne glasses) for the peacemaker glasses
/:cl:

Гуччи линзы 150 кредитов на глазах

---

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm
_maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm

Добавил фракцию в турельки, чтобы они не стреляли по своим. А ещё чуть поменял зоны на лавалендском интердайне и теперь консолька оповещает о проснувшихся. Ура.
Фикс багов
<details>
</details>
:cl:
fix: fixed Interdyne turrets and waking up announcements
/:cl:

Фикс турелей и анонса проснувшихся на интердайне

---

code/game/turfs/closed/minerals.dm

Отключаем зависимость шанса на руду и её количества в жиле от расстояния до рудного вента. У нас есть пинпоинтеры, больше жопная боль с поисками жил по концентрации руды не нужна.
Приятнее играть за шахтёра. Особенно на айсбоксе.
<details>
</details>
:cl:
balance: ore spawns (inside turfs) no longer dependent on proximity of ore vents
/:cl:

Спавн руды вновь более независим от положения относительно рудных вентов.

---

tff_modular/master_files/code/modules/job/job_blacklist.dm

Добавляет в черный список должностей ГБСов новые профессии (ветеран СБ, ассистент мостика, битраннер и сисадмин)
Плюсы:
\+ не нарушает логику расы
Минусы:
\- жуки не получат награды и уважения после битв в Гайе
<details>
</details>
:cl: mogeoko
balance: Blacklisted new jobs for GAS
/:cl:

GAS jobs blacklist update

---

tff_modular/modules/redsec/code/vending.dm
tff_modular/modules/redsec_reskins/code/redsec.dm

У нас и в вендомате, и вообще была блюсек юбочка СБ, которая как туртлнек, но в альтскинах её были только баттлдресс и редсек. Я добавил к альтскинам саму имеющуюся юбочку + её черный вариант + plain вариант юбочки в вендомат.
+очки стиля
+возможность задирать рукава (раньше задрать рукава ты не мог, потому что в альтскинах не мог выбрать нужный вариант)
<details>
</details>
:cl:
add: adds bluesec skirt altskins and blusec plain skirt in vendomat
/:cl:

owo юбочки для uwu сесурити

---

modular_nova/modules/colony_fabricator/code/design_datums/tools.dm
modular_nova/modules/company_imports/code/armament_datums/akh_frontier.dm

Ограничивает доступ к лому для вскрытия дверей. Ста кредитов и лёгкого крафта точно не должно быть для него.
Баланс открывашки, которую нельзя объяснить "Это жи ж лом!!1!" у какого-нибудь парамедика или офицера, что заказал себе за 100 кредитов.
Код
:cl:
balance: Prybar was removed from Rapid Construction Fabricator and cargo imports. Now, it can be found only in ruins.
/:cl:

Balance: prybar only in ruins

---

tff_modular/modules/drinks/skrelluq/reagent.dm

Добавлен легкий наркотический эффект напитку Skrelluq и уменьшено количество *wurlbe за глоток до 2-3 (было 13).
(Мне точно не угрожали расправой за спам *wurble)
Поверьте мне
:cl:
fix: tweak skrelluq *wurble count (2-3 per 5u) and added some narcotic effect
/:cl:

tweak(skrelluq): add some narcotic effect & reduce *wurble count

---

tff_modular/modules/drone/code/droneDispenser.dm
tgstation.dme

Отключение автоматического производства дронов выставлением максимума оболочек "-1".
Защита от набегаторов и нарушителей на дронах.
<details>
Вишня ЕРПшка требует видео именно тут
производит дронов только при изменении значения maximum_idle с -1 на любое другое
https://github.com/user-attachments/assets/290ab8e5-bbe5-4c44-afe0-2ba96d701608
</details>
:cl:
del: Maintenance drones now are unavailable
code: Changed max drone shells to "-1" 
/:cl:

Making max drones "-1"

---

tff_modular/modules/redsec_reskins/code/redsec.dm

Фикс и добавление редсек вариации для ботинков и разгрузки миротворца. Также добавлены ред- и блусек перчатки с ТГ. Технически, редсек вариация разгрузки - версия разгрузки для ЕРТ Армадайна, но их никогда никто не видел у нас на сервере. Это миф.
БОЛЬШЕ РЕДСЕКА БОГУ РЕДСЕКА
<details>
</details>
:cl:
add: Added redsec versions for security boots and peacekeeprs webbings.
add: Added TG security gloves as new skins.
/:cl:

Микроапдейт редсека

---

.github/workflows/auto_changelog.yml
.github/workflows/compile_changelogs.yml
.github/workflows/update_tgs_dmapi.yml

Лень - двигатель прогресса. Но в данном случае - его стопор. Мы не используем этот `actions/create-github-app-token` и чейнджлоги у нас вообще генерируются под профилем вишни. Оставим пока как есть - то есть, вернём старую переменную секрета.
<details>
</details>

"Фикс" авточейнджлогов

---

modular_nova/master_files/code/modules/antagonists/heretic/knowledge/general_side.dm

https://github.com/Fluffy-Frontier/FluffySTG/pull/3520
Отключает модулярную правку анвара с Новы. Она теперь не имеет смысла, так как защиты дорм у нас уже давно нет.
Еретики больше не будут получать фри вознесение просто потому, что они каждую "сложную" цель заменили на "простую".
<details>
</details>
:cl:
balance: heretic target reroll once again costs knowledge to perform
/:cl:

Возвращение стоимости в заниях спелла на реролл целей еретика

---

_maps/map_files/NSSJourney/NSSJourney.dmm

hh beep bip
ПР вносит следующие изменения:
Обновление интерьера: 
> офис АВД, зал суда, бар, санитарные помещения, фитнес-зона, коридор между фитнес-зоной и санитарными комнатами, кабинет мима и клоуна, гражданская гидропоника и изолятор.
Другие изменения: 
> Коридор между санитарными помещениями и крио незначительно расширен.
> Офис АВД уменьшен для увеличения площади зала суда.
> Пространство гражданской гидропоники было слегка сокращено.
> Добавлен переходной коридор между офисом НТР, бригом и камерой суда.
> Скорректированы несколько дверей с стандартными названиями шлюзов и названиями "s."
> Добавлены недостающие доступа для нескольких дверей внутри брига.
<details>
<summary>Основные различия</summary>
[NEW
[OLD
</details>
<details>
<summary>Гидропоника и изолятор</summary>
[NEW
[OLD …

Небольшой ремап NSS Journey / Box Station.

---

code/modules/antagonists/heretic/items/heretic_blades.dm
code/modules/antagonists/heretic/knowledge/lock_lore.dm
code/modules/antagonists/heretic/magic/blood_cleave.dm
code/modules/antagonists/heretic/magic/blood_siphon.dm
code/modules/antagonists/heretic/magic/furious_steel.dm
code/modules/antagonists/heretic/magic/mind_gate.dm
code/modules/antagonists/heretic/magic/void_phase.dm
code/modules/antagonists/heretic/magic/void_pull.dm
code/modules/antagonists/heretic/status_effects/mark_effects.dm
code/modules/antagonists/nightmare/nightmare_equipment.dm
code/modules/antagonists/voidwalker/voidwalker_void_eater.dm

Урон еретических серпов поднимаем с 20 до 28, проклятого серпа с 25 до 32
Поднимаем урон многих боевых заклинаний еретика на 10-15
Еретик пепла теперь кидает в стаминакрит при ударе по метке как и должен
Поднимаем урон light eater с 25 до 30
Поднимаем максимальный урон void eater с 25 до 35
Путь ключа имеет больше шанс вызвать критический кровоток
"Крысопушки имба" и так далее, как одно из возможных решений поднятие статов у обязательных антаг вещей с ТГ.
Пару измененных циферок, не столь сложно
<details>
</details>
:cl:
balance: Damage buffs for herethic, void walker and nightmare items or spells
/:cl:

Поднимаем урон ТГ антагов (в поисках идеала в баладе о крысопушках)

---

tff_modular/modules/~donator/loadout.dm

Просто удаляет привязку к сикею. Вместо неё предметы теперь просто для донатеров. Потому что да.
:cl:
add: Several ckey locked cosmetic item are now unlocked for every donator
/:cl:

Удаление сикей лока на предметы zanozkin

---

code/game/objects/items/stacks/bscrystal.dm

Теперь телепортирование на БС кристалах будет накидывать 15 отвращения за каждое применение, для понимания 50 отвращения дает шанс начать блевать, муддебаф и экран начинает крутить. Ну и да, меня попросили перекинуть этот ПР сюда.
Меньше антагов на миллионе БС кристалов уху!!
Я проверил, облевал все что можно!!
<details>
</details>
:cl:
balance: bluespace crystals now stack disgust on use
/:cl:

Нерф телепортирования при помощи БС кристалов

---

code/modules/antagonists/traitor/uplink_handler.dm

Отключаем возможность брать и выполнять побочки у триторов
Тритор не будет превращаться в мажора по первому пику, побочки были одной из раковых опухолей
<details>
</details>
:cl:
balance: Traitors cannot take secondary objectives anymore
/:cl:

Деактивация выбора побочек у триторов

---

tff_modular/modules/tgmc_xenos/code/base_nova_xeno.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/defender.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/drone.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/praetorian.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/queen.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/ravager.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/rouny.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/sentinel.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/spitter.dm
tff_modular/modules/tgmc_xenos/code/xeno_types/warrior.dm

Исправляет баг из-за которого некоторые ксеносы не могли строить и создавать резину.
Так же были убраны последние следы новы: например `/datum/action/cooldown/alien/acid/nova` стал `/datum/action/cooldown/alien/acid/tgmc` и т.д.
Убрано бесполезная кнопкая для Rest (непонятно, зачем нужно 3-я кнопка для этого действия, если для него есть кнопка снизу справа и верб в статпанели).
И было небольшое изменение баланса (которое никто не заметит, ведь этих ксеносов еще не трогали): невидимость у всех ксеносов, кроме королевы, была убрана.
Исправление бага.
Изменение способности становиться невидимым связана с тем, что эти ксеносы и так достаточно сильные. А если еще и дать им всем возможность быть люркером (которого у нас, к счастью, нет) - это уже слишком. Королеве оставлено по двум причинам: …

Еще пара фиксов для ксеносов

---

tff_modular/modules/uplink_item/code/categories/ammuniton.dm
tff_modular/modules/uplink_item/code/categories/dangerous.dm

Бульдог, ЦР привязаны к прогрессии, выпилены дубликаты у нюкопс, лоноп аплинков
<details>
</details>
:cl:
balance: удалены дубликаты из аплинков, Ц20Р привязан к прогрессии 30 минут, Бульдог привязан к прогрессии 45 минут
/:cl:

Бульдог, ЦР привязаны к прогрессии, выпилены дубликаты у нюкопс, лоноп аплинков

---

modular_nova/modules/company_imports/code/armament_datums/sol_defense.dm

Убирает Скильд и Такбок из карго, оставляя его только у НТРа как табельное.
По заказу Яжрета. Револьвер, ебущее живое и неживое, ломающее постройки и имеющее 40 дамага за выстрел. Тот самый револьвер, который как основное оружие у некоторых ОБР, ЦКшников и Армадайна, в свободном владении как табельное оружие закупается СБшниками каждый раунд. Теперь этого не будет.
-
:cl:
balance: После несчастного случая с покушением на лейтенанта ЦК со стороны инженера с применением крупнокалиберного револьвера Скильд, НаноТрейзен принял решение наложить вето на поставку образцов вооружения данного калибра (Défonce и Défenestreur)на территории научных станций во избежании дальнейших покушений на высокопоставленных лиц из-за невозможности регулировать оборот высоколетального оружия, что считается …

bye bye skild

---

modular_nova/modules/company_imports/code/armament_datums/nri_military_surplus.dm

Возвращение Защитника в карго.
Теперь это тактическое оружие и регламентируется согласно нему.
:cl:
balance: Защитник вернулся в поставки и снаряжение СБ в качестве тактического оружия, что не даёт его свободно заказывать и применять в Зелёный Код.
/:cl:

Zashch returns

---

modular_nova/modules/company_imports/code/armament_datums/nri_military_surplus.dm
modular_nova/modules/company_imports/code/armament_datums/sol_defense.dm
modular_nova/modules/sec_haul/code/guns/armory_spawns.dm

Возвращает магазин к Защеку
Восстанавливает штурмовую винтовку к покупке
Актуализация с вики
-
:cl:
balance: Магазины к Защитнику наконец тоже доступны в карго.
balance: Штурмовая винтовка Сола возвращена как вариант тактического оружия и восстановлена к заказу через карго.
/:cl:

Fixed sol rifle and Zashch ammo

---

modular_nova/modules/barricades/code/barricade.dm

ПР в ветку `ssss`, не `master`
Просто удаляем эти штуки при инициализации + из коробки с барикадами, чтоб сбухи не ставили их и не крашили на секунду клиенты всем

Фикс крашей барикад))

---

tff_modular/modules/crucible_soul_potion_rebalance/crucible_soul_tweak.dm
tgstation.dme

Данный ПР добавляет эффект "воздержания", который применяется по окончанию эффекта зелья "ноуклипа". Этот эффект запрещает использовать это зелье на протяжении 300 секунд (5 минут).
Сверху этот ПР запретит продлевать эффект зелья, пока он работает.
ПР превратит это зелье из абузного в утилитарное, которое еретик будет использовать для того, чтобы достать спрятанную цель или врага, не позволяя бесконечно находиться в бесплотной форме.
<details>
</details>
:cl:
balance: Brew of the crucible soul (еретическое зелье для прохождения сквозь стены) теперь по окончанию эффекта накладывает эффект "воздержания" на 5 минут, который не позволяет его употреблять.
balance: Brew of the crucible soul (еретическое зелье для прохождения сквозь стены) теперь нельзя выпить, …

[МОДУЛЬНО] Нёрф/ребаланс еретического зелья прохождения сквозь стены.

---

code/modules/mob/dead/new_player/new_player.dm
tff_modular/modules/observing/observing.dm
tgstation.dme

Просто добавляет верб для переключения возможности Observe-иться. Админы и ивентологи могут обойти это. Так же добавляет "станционный трейт", который автоматически отключает Observe. Трейт не раундомный, его можно выдать только педально кнопками
Повторюсь, вне ивентов это НИКАК не появляет на людей. Абсолютно.
Literally 1984.
Нам очень надо иногда для ивентов это... На игроков в самих раундах никак не влияет
<details>
Для педалек
</details>
:cl:
admin: Now Admins can disable the Observe button in the lobby for players
/:cl:

Возможность отключить для игроков кнопку Observe в лобби 

---

tgui/packages/tgui-say/516/TguiSay.tsx
tgui/packages/tgui-say/516/constants.ts
tgui/packages/tgui-say/516/helpers.ts
tgui/packages/tgui-say/516/styles/colors.scss

Руссифицирует все префиксы чата. Даже ранее нерабочие алиумские, генокрадские и ТД. Теперь обработка идёт на фронте. Так же пофикшен недостающий стиль канала ивентеров (не тестил, лень)
<details>
</details>
:cl:
add: russian radio prefixes are now fully handled in tgui-say. Enjoy your :т and :г
fix: fixed missing eventologist style for tgui-say
/:cl:

Руссификация префиксов чата + микрофикс

---

tff_modular/modules/gun_balance/shotgun.dm

Делает катюшу и производные ему (Jager, Shitzu) двуручными, также запрещает их вешать на пояс, только на спину, как и все дробовики.
Одноручный автоматический барабанный дробовик, ну куда еще?
:cl:
balance: делает катюшу и производны ему дробовики двуручными и запрещает носить на поясе
/:cl:

tweak katyusha/ weight

---

.github/workflows/compile_all_maps.yml

вроде поэтому она преждевременно прекращается

Поднимаем время таймаута проверки на карты до 10

---

tff_modular/modules/gun_balance/pistols.dm

Веспа теперь пистолет который стреляет одиночными. нет смысла все еще выдавать ему штраф к точности.
снова можно использовать пистолет и не промазывать
<details>
</details>
:cl:
balance: к гуэпэ приварили обратно мушку
/:cl:

Разнерф веспы

---

.github/workflows/compile_all_maps.yml
_maps/_basemap.dm

Никак влияет ни на что для игроков. Должно уменьшить нагрузку на тесты, проходящие на серверах нашего любимого гитхаба (и избавить меня от нужды перезапускать их по 10 раз)

Отключаем компиляцию карт тг

---

modular_nova/modules/contractor/code/items/modsuit/theme.dm

По какой-то неизвестной мне причине, замедление у МОДа контрактора равно 0.5, что равно офицерскому.
МОД контрактора не должен замедлять так сильно, учитывая что у контрактора нет альтернативной брони, на которую он может заменить МОД.
Убирает полностью замедление до 0.0
Инвалиды станут менее инвалидными.
<details>
</details>
:cl: SaukyKouko
balance: МОД контрактора больше не замедляет
/:cl:

МОД контрактора больше не замедляет.

---

tff_modular/master_files/code/modules/cargo/markets/market_items/weapons.dm

Теперь при покупке на черном рынке мы получаем НЕ пустую коробку
<details>
Проверил. Отвечаю. Всего пять-шесть символов изменений емае
</details>
:cl:
fix: the skild AKA Defenestereur actually spawns after black market purchases
/:cl:

fix the defenestreur blackmarket kit not spawning

---

.github/workflows/gbp.yml
.github/workflows/gbp_collect.yml

Дает возможность отключать рабочие потоки, связанные с GBP, при этом не используя грубое отключение потока на самом гитхабе
Почему это хорошо? 
К сожалению, на апстримах автолейблер находится в одном рабочем потоке, что и штука, связанная с GBP. Вообще, эту штуку можно вполне отключить, но для этого проверяется секрет ACTION_ENABLER. Но этот секрет так же отвечает и за авточенджлог. Поэтому я просто поменял проверку с наличия секрета ACTION_ENABLER, на проверку секрета GBP_ENABLER (конечно можно просто закомментировать, но я выбрал такой вариант). Это позволит включить рабочий поток Label and GBP и он не будет выдавать ошибки
Как альтернативу можно создать свой рабочий поток с автолейблером... Но, как по мне, это не очень надежно, ведь он будет привязан к другому файлу в коде. Если …

Менее радикальный способ отключить ГБП

---

tff_modular/modules/admin/verbs/notes_panel.dm
tgstation.dme

Кто-то давно просил (Алекс), я давно сделал, но что-то совсем забыл сделать ПР
Ничего особенного - просто открывает нотесы самого себя
Админам не надо жать ПКМ по случайной кукле -> Player Panel -> Notes, чтобы открыть эту менюшку
Оно работает, проверено в том числе с подключенной ДБ.
<details>
</details>
:cl:
admin: added new way to open notes panel
/:cl:

Useless notes panel

---

modular_nova/modules/modular_weapons/code/company_and_or_faction_based/szot_dynamica/ammo/pulse.dm
modular_nova/modules/modular_weapons/code/company_and_or_faction_based/szot_dynamica/magazines.dm
modular_nova/modules/modular_weapons/code/company_and_or_faction_based/szot_dynamica/pulse_rifle.dm
modular_nova/modules/modular_weapons/code/company_and_or_faction_based/szot_dynamica/pulse_sniper.dm

ПР сделан по предложке
БЫЛО -> СТАЛО
pulse_rifle
Damage multiplier: 1 → 0.8
Spread: 1 → 3
Magazine: 60 → 30
pulse_sniper
Damage multiplier: 2 → 1.5
Projectile speed: 2.5 → 2
Spread: 2.5 → 3
Убирает оружие из SSR тира и дополнительно ВОЗМОЖНО фиксит баг с лишними 15 патронами при спавне пушки.
Оружие сильно багует, к сожалению.
<details>
https://github.com/user-attachments/assets/41dc9926-4753-4d5a-9d59-3cce1a7039b8
</details>
:cl:
balance: Spread, damage, speed and nerfs to Zaibas weaponry.
/:cl:

DeZaibas - послабление пулемета и снайперской пульсовки.

---

_maps/map_files/NSSJourney/NSSJourney.dmm

Третий пакет санкций против оригинального маппера журни. Правит несколько декалей в стенах, добавляет в робо лампу... по сути, всё. Ещё поворачиваем лампу в токсинке чтобы не смотрела на стол и убираем лампу со стекла в ксенбио.
Мы победили лрп лампы в воздухе, наверное.
Никаких крупных изменений... просто лампа в робо, пару декалей туда-сюда
Можно на третий раз забить просто не?
:cl:
map: Fixes minor issues with NSS Journey
/:cl:

Fix nss journey pt3

---

code/modules/mob/living/basic/space_fauna/demon/demon_subtypes.dm
code/modules/spells/spell_types/jaunt/bloodcrawl.dm

Демон резни больше  не умирает от того, что находится в джаунте.
Урон увеличен с 15 до 20.
Фишка с "получением урона в джаунте" была добавлена чтобы демон резни играл активно, и в условиях ТГ это звучит адекватно - повсюду кровь, хаос и вряд ли кто-то будет заниматься уборкой крови когда тебе маг сырный круг на мостике рисует.
Но что мы видим на ФФ? На фф при обнаружении демона все силы идут на чистку пола, из-за чего демон умирает тупо от того, что не нашел кровь)). Если нет других антагов, демон резни становится бесполезным. А 15 урона это тупо смешно, даже у пауков больше урона.
<details>
</details>
:cl:
del: Убран урон от нахождения в джаунте у демона резни.
balance: Урон демона резни увеличен на 5 единиц.
/:cl:

наплак демона резни
