Fluffy-Frontier/FluffySTG

tools/build/build.js
Возвращает возможность билдится в случае изменений только в модульной папке ФФ
Никак, абсолютно.
чево
<details>
</details>
=> watch updates in ff folder to build

tff_modular/modules/discord/discord.dm, tgstation.dme
Да. Верификация через дискорд и игру.
Да.
<details>
</details>
=> Discord Verify

.github/workflows/ci_suite.yml, fluffy/tools/fluffy_check_grep.sh, tools/validate_dme.py
чегоооо
рп будет хрп
<details>
</details>
=> юнит тесты спаси и сохрани

modular_skyrat/modules/automapper/code/area_spawn_entries.dm, modular_skyrat/modules/emotes/code/emotes.dm
Маленькие правки.
Задержка в эмоутах не 5 секунд, а 2. 
Убираем ЕРП автомат из общежития. 
Пожалуйста, не спамте. 
Их не будет.
:cl:
del: Removed LustWish Vend from dormatories
code: Emotes cooldown from 5 to 2
/:cl:
=> Emotions cooldown and ERP vendor removal

code/modules/holiday/holidays.dm
Pride Week не начнется. Пока что.
Да.
Нет.
<details>
</details>
:cl:
del: Removed pride week holiday.
/:cl:
=> lgbtqwerty+-*= week no more.

code/modules/client/preferences/middleware/jobs.dm, code/modules/client/preferences/middleware/quirks.dm, tff_modular/modules/quirks/code/_quirk.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
Очередная задачка, которую мне сказали сделатб, иначе саша бомбом. Я не знаю что за Александр и почему он бомб-бом...
А хер знает, я спасаю Александра. 
Нет времени тестировать! САНЯ ЖИВИ!!!
:cl:
add: now donators can get oversized quirk
code: now veteran's quirks can be picked by donators, if it's allowed!
/:cl:
=> Нашествие великанов

interface/skin.dmf
Хотфикс. Возвращаем старый рунчат. Остальное не трогаем.
<details>
<summary>Ага, вот тут надо тыкнуть.</summary>
</details>
:cl:
code: hotfix for runechat
/:cl:
=> Fix for runechat.

code/modules/language/language_holder.dm, code/modules/mob/living/silicon/silicon.dm
Вернем знание языков ИИ. Привет Авионе из подвала.
<details>
</details>
:cl:
add: returns languages for all silicones except cyborgs
/:cl:
=> Silicones and their languages

code/modules/antagonists/traitor/objectives/infect.dm
Балансим одну из задач антагониста. Причина: грифозно.
Done. И еще не кладет игру. Клево!
:cl:
balance: task "infection" now using random disease. No HMS.
/:cl:
=> Balance Traitor Task with Hereditary Manifold Sickness

_maps/map_files/KiloStation2/KiloStation2.dmm
Обновляет путь к симплу медведя на килостанции и убирает рантайм из-за неправильной переменной в полу.
Поможет, верьте мне.
<details>
Зелёная галочка в ПРе является докаазтельством
</details>
изменение не заслуживает того, чтобы быть в чейнджлоге.
=> Simple bear to basic bear on kilo

tff_modular/modules/autoaccent/code/autoaccent.dm
Исправление бага с автоакцентом.
Место pick_dog(cat)_rawr будет ррррррр
<details>
</details>
:cl:
fix: Fixed auto-accent on 515
/:cl:
=> Adds PROC_REF into CALLBACK

modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
Added another person due to really dumb oversight on myside. 
<details>
</details>
=> [DONATOR] Holocigar Ckey Add

modular_skyrat/modules/company_imports/code/armament_datums/sol_defense.dm, modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/rifle.dm
Работа по ТЗ. Ничего интересного.
Убрали машинган. Убрали винтовку.
Порезали урон марксманки до 29,75.
А еще убрали магазин на 60 патрон.
<details>
<summary>Всё сделано по ТЗ</summary>
</details>
:cl:
balance: The part of sol rifles are no longer available for purchase in cantraband cargo.
/:cl:
=> Rebalance Sol Rifles

tgui/packages/tgui/interfaces/Biogenerator.tsx, tgui/packages/tgui/interfaces/PaperSheet.tsx
Я накосячил и не обновил ветку в этом ПРе. https://github.com/Fluffy-Frontier/FluffySTG/pull/1480 Ну. Бывает.
=> [Re-mirror]Hotfix for paper tgui crash 

_maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/tramstation/tramstation.dmm, _maps/virtual_domains/clown_planet.dmm, code/__HELPERS/visual_effects.dm, code/controllers/subsystem/modular_computers.dm, code/datums/components/crafting/tailoring.dm, code/game/objects/items/grenades/plastic.dm, code/game/objects/items/tools/weldingtool.dm, code/modules/cargo/packs/emergency.dm, html/changelogs/AutoChangeLog-pr-80622.yml, html/changelogs/AutoChangeLog-pr-80712.yml, html/changelogs/AutoChangeLog-pr-80718.yml, html/changelogs/AutoChangeLog-pr-80771.yml, html/changelogs/AutoChangeLog-pr-80793.yml, html/changelogs/AutoChangeLog-pr-80795.yml, html/changelogs/AutoChangeLog-pr-80801.yml, html/changelogs/AutoChangeLog-pr-80803.yml, html/changelogs/AutoChangeLog-pr-80810.yml, tgui/packages/tgui/components/VirtualList.tsx, tgui/packages/tgui/components/index.ts, tgui/packages/tgui/interfaces/AirAlarm.tsx, tgui/packages/tgui/interfaces/CommunicationsConsole.jsx, tgui/packages/tgui/interfaces/Fabrication/DesignBrowser.tsx, tgui/packages/tgui/interfaces/Techweb.jsx
https://github.com/NovaSector/NovaSector/pull/364
Когда-нибудь мне будет не лень пойти и научиться делать шелл-скрипты, чтобы бот не умирал на мердж-коммитах.
=> [Manual Mirror] Nova PR 364

tff_modular/modules/deforest_implants/code.dm, tgstation.dme
Четыре импланта новых ДеФореста, теперь можно купить только с внутренних консолей карго. Кибердека при этом требует взлома консоли для доступа к контрабанде. А еще, чтобы распечатать ее техфабе нужны исследования нелегала.
Чуть ужесточает контроль за распространением имплантов, которые задумывались как боевые. Карго могут решать, кто заказывает эти импланты. Теоретически. 
Поверьте мне, я инженер
<details>
</details>
:cl:
balance: deforest cyber implants are bought from restricted consoles
balance: deforest cyber deck is bought from contraband access and requires illegal tech to craft.
/:cl:
=> Твик имплантов DeForest Medical Foundation

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm, _maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm, _maps/map_files/IceBoxStation/FrozenFields.dmm
Virology disposals, shower door bolts, slime processors, vendomats n etc fixes, some deco corrections and some extra stuff shuffled/added.
Lika blackbox at nova server cause its kinda nice idea.
Bugfixes are nice. Especially when tey are not that late as this one.
Mark my word.
:cl:
fix: Interdyne map fixes, ql changes + Blackbox Recorder. 
/:cl:
=> Some sweet Interdyne bugfixes.

tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/tff/character_voice.tsx
Всё началось в далёком 2013... Тогда вышла в свет игра The Stanley Parable, где Главный Герой работал в офисе и его задачей было нажимать кнопки.......... С тех пор я очень полюбил кнопки................... Я решил, что я тоже хочу создавать кнопки, а потом нажимать на них, поэтому занялся так называемым программированием. Знаете, мой дед тоже был  своего рода кнопкой. 
Так вот, если переходить ближе к делу, то я заметил, что искать подходящий блупер не очень удобно. Мой мозг пронзило осознание того, что настал момент к которому я готовился все 14 лет своей жизни: к созданию кнопок. Так, я зашел в вс код и добавил к выпадающему меню кнопки и изменил высоту кнопки проигрыша звука до 88%, чтобы ебать здоровой (как Папич) она не была, а то ВЫПАДАЮЩЕЕ МЕНЮ СЖАЛОСЬ КАК БУДТО БЫ КАК-ТО, А …
=> Кнопкщещ для графы выбора звука блупера

tff_modular/modules/quirks/code/_quirk.dm
Прописывает квирку на пины флаг "спрятано". То есть они будут недоступны для взятия. Самый просто способ убрать их? так как более никак их не получить.
Гейство будет запрещено. Pride month is over. Stop being gay.
:cl:
balance: you can't take pride pin quirk anymore.
/:cl:
=> Убирание квирка на лгбткаттакхеликоптер пины.

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm, _maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm
Fixes icebox interdyne prices, some deco and adds some random little things.
Fixes are nice.
:cl:
fix: fixed a few things
/:cl:
=> Dyne fixes4

tff_modular/modules/blueshield-rearm/code/projectiles.dm
Сокращаем технический долг, делая количество выстрелов револьвера зависимым от заряда батареи. Фиксим тот факт, что револьвер сейчас имеет 8 000 выстрелов на одной выданной раундстарт батарейке. Увы.
Ну это баг типо.
<details>
</details>
:cl:
fix: fixes SR-8 revolver having virtually unlimited ammo
/:cl:
=> Фиксим тот факт, что револьвер щита может сделать восемь тысяч выстрелов на одной Т2 батарейке

tff_modular/modules/~donator/clothes/donator_clothing.dm
https://www.youtube.com/watch?v=xUMylxKYDq0
=> Эти ворн айконы должны быть вне закона.

tff_modular/master_files/code/datum/quirks/negative_quirks/burr.dm, tff_modular/master_files/code/datum/quirks/neutral_quirks/burr.dm, tgstation.dme
Заказано: https://discord.com/channels/574254221004898335/1237411415468544030/1237411415468544030
Всё ради Пиво.
:cl:
add: New quirk R-less
/:cl:
=> Квирк картавости.

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm, _maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm
Secret formula and Sansufentanyl thingys. Icebox modsuits, xeno slidedoors and some deco. 
Fixes are nice. Pity that imma so slow n lazy. Paw-paw.
<details>
</details>
:cl:
add: Interdyne secret formula and Sansufentanyl ingridients.
fix: Dyne deco fixes.
/:cl:
=> Some more Interdyne changes.

_maps/_basemap.dm, _maps/map_files/KiloStation2/KiloStation2.dmm, _maps/map_files/NSSJourney/NSSJourney.dmm
Исправляем тот факт, что кило и джурне не компилировались в Compile Maps напротяжении полугода и больше. УПС. Плюс фиксит некоторые проблемы с удалёнными старыми консольками карго.
Никак
Если будет зелёная галочка и Кило с Джурне компилировались в Compile Maps - всё работает.
Не касается игроков
=> [CI] А вы знали, что карты надо добавлять в список, чтобы они компилировались в юнит-тесте для карта? А я вот не знал.

tff_modular/modules/blueshield-rearm/code/wt550.dm
missed `src` moment. Пули с их уроном взяты с крыс. 17 стамина-дамага. Ха. Ха.
Щит сможет стрелять по ассистентам не боясь ПМок.
<details>
</details>
=> Исправляем мой факап со спауном ВТшки у щита + добавляем ему резиновые пульки

tff_modular/modules/character_directory/character_directory.dm, tgstation.dme
Подрезаны гендеры, ориентации и ||ЗАПРЕЩЕНО РКН||. Модульно, конечно же.
Скрепы держатся.
<details>
</details>
=> Ущемление гендерного разнообразия

code/modules/surgery/surgery_step.dm
Увеличение времени операции на пациенте в стазисе в пять раз.
Меньше тех самых медиков лечащих на стазисах
Работает, это 3 строчки кода все же.
<details>
</details>
:cl:
balance: surgery while stasis now much much longer
/:cl:
=> Stasis surgery nerf

tff_modular/master_files/code/modules/mapping/space_ruins.dm, tgstation.dme
Ну забавная ролька для спеси тайда. Просят её часто. Пусть будет с флагов "всегда спавнится"
Больше возможностей для игрыз а торговца повысят возможность за него взаимодействовать со станцией
<details>
</details>
:cl:
balance: blackmarket dealer now spawns everytime
/:cl:
=> Блекмаркет будет спавниться всегда

code/modules/research/techweb/nodes/research_nodes.dm, modular_nova/master_files/code/modules/research/techweb/all_nodes.dm
Баланс Боевого сердца: Перемещение его в отдел к остальным имбовым кибер-органам.
Предотвращает манч и злоупотребление, ибо сердце даёт слишком много преимуществ как для органа, что открывается в исследовании Advanced Anomaly Shells.
Код
+
<details>
</details>
:cl:
balance: Moving Voltaic Combat Cyberheart from "Advanced Anomaly Shells" to "Combat Cybernetic Organs"
code: "Combat Cybernetic Eyes" was renamed to "Combat Cybernetic Organs"
/:cl:
=> Balance: Voltaic Combat Cyberheart

.gitignore, code/__HELPERS/atoms.dm, code/__HELPERS/reagents.dm, code/datums/status_effects/debuffs/staggered.dm, code/game/objects/effects/decals/remains.dm, code/game/objects/effects/spawners/random/structure.dm, code/game/objects/items/storage/holsters.dm, code/modules/fishing/fish/_fish.dm, code/modules/fishing/sources/source_types.dm, code/modules/modular_computers/computers/item/disks/role_disks.dm, code/modules/modular_computers/computers/item/disks/unique_disks.dm, code/modules/modular_computers/computers/item/pda.dm, code/modules/modular_computers/computers/item/role_tablet_presets.dm, code/modules/modular_computers/file_system/programs/crewmanifest.dm, code/modules/modular_computers/file_system/programs/records.dm, code/modules/modular_computers/file_system/programs/statusdisplay.dm, code/modules/projectiles/projectile.dm, html/changelogs/AutoChangeLog-pr-86016.yml, html/changelogs/AutoChangeLog-pr-86023.yml, html/changelogs/AutoChangeLog-pr-86027.yml, html/changelogs/AutoChangeLog-pr-86070.yml, html/changelogs/AutoChangeLog-pr-86095.yml
Includes all of the TG PRs on 8/29 up until this point.
Autochangelogs included
https://github.com/NovaSector/NovaSector/pull/4333
=> Batch of TG PRs 8/29 (#4333)

README.md
ИЗ-ЗА ЭТОГО ЧЕЛОВЕКА Я НЕ СПЛЮ: @AnywayFarus 
Актуализированная схема и починенная ссылка на гайд по модуляции
<details>
[ПИКЧА](https://i.imgur.com/lgbYurx.png)
</details>
=> ReadMe - обновление о контрибьюции

modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm, tgstation.dme
Возврат общих шмоток из лодаута
<details>
</details>
:cl:
fix: Nova's loadout items were returned.
/:cl:
=> Return free Nova loadout

tff_modular/modules/~donator/loadout.dm
Добавил сикей Якапички в донатную шмотку Ромонтески.
Мне за это сказали спасибо. Как всегда.
<details>
</details>
=> Updated donator item

code/__DEFINES/is_helpers.dm, code/modules/mob/living/basic/farm_animals/bee/_bee.dm, code/modules/reagents/reagent_containers.dm, code/modules/reagents/reagent_containers/cups/_cup.dm, code/modules/reagents/reagent_containers/misc.dm, code/modules/reagents/reagent_containers/spray.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/bee.dm, html/changelogs/AutoChangeLog-pr-87150.yml, html/changelogs/AutoChangeLog-pr-87151.yml, html/changelogs/AutoChangeLog-pr-87163.yml
https://github.com/NovaSector/NovaSector/pull/4469
=> Batch of TG PRs 10/11 part II (#4469)

tff_modular/master_files/code/modules/job/job_blacklist.dm
Тешарьбам обрезана возможность быть ГСБ, офицером, и щитом.
Бриг больше не сможет использовать ГСБ для игры в футбол??? Наверное..
<details>
</details>
:cl:
del: Teshari can not join round as HoS, Security Officer and Blueshield.
/:cl:
=> Teshari job limitations

tff_modular/modules/vending/vends/autodrobe.dm, tff_modular/modules/vending/vends/clothing.dm
Фикс названия переменной для категории
Все предметы на месте
:cl:
fix: product_categories to product_categories_ff
/:cl:
=> Quickfix ff_categories

modular_nova/modules/modular_weapons/code/company_and_or_faction_based/saibasan/laser_guns.dm
Ускорил перезарядку, чтобы офицеры не тащили мощь 11 стволов в сумке
Не будет провоцировать манч
:cl:
balance: changed charge_delay to 7
/:cl:
=> [TM-ONLY] Ребаланс хуйсонга и хоши

tff_modular/modules/~donator/loadout.dm
Добавил сикей чмохи к своему плащу.
Я получил профит в виде отработки на локалке.
<details>
</details>
=> Fluff ckey addition

config/maps.txt
Фикс нашего конфига спустя несколько месяцев
=> Fix conflict in config

_maps/map_files/NSSJourney/NSSJourney.dmm
Simply fixes:
- Наименования шлюзов общественных санитарных помещений;
- Проводку в прибытии и зале ожидания между гаупвахтой, НТРом, Синим Щитом и судом;
- Мусоропровод бара.
UPD: - Удален общий доступ в инженерное фойе со стороны технических тоннелей.
:cl: Smol42
fix: fixed some minor issues.
/:cl:
=> Minor Box Station fix

tff_modular/modules/snowfall/snowfall.dm, tgstation.dme
По факту погода для ивента... Но я думаю можно и оставить насовсем?
Добавляет погоду - снегопад. Он не так сильно перекрывает обзор, как снежная буря и не наносит урона (можно если что включить урон)
Сама не спавнится, только кнопочно
Бесконечная длится бесконечно, пока педальки не отрубят. Временная от 3 до 5 минут.
Аутентично для ивентов или просто так!
<details>
</details>
:cl:
add: new weather - snowfall
/:cl:
=> Новая погода - снегопад

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm
Добавляет переменную `all_products_free` для всех вендоматов в зимнем куполе интердайна
У интердайн коммунизм, они не могут платить за продукцию в вендоматах.
:cl:
fix: fixed icemoon interdyne employees having to pay for their clothes and tools
/:cl:
=> "Update icemoon_interdyne_base_ff.dmm" или "вендоманты у дайна вновь бесплатные"

code/game/objects/structures/aliens.dm, code/modules/mob/living/carbon/alien/special/alien_embryo.dm, code/modules/mob/living/carbon/alien/special/facehugger.dm, tff_modular/modules/tgmc_xenos/code/alien_egg.dm, tff_modular/modules/tgmc_xenos/code/xeno_types/queen.dm, tgstation.dme
Делаю то, что должен был сделать раньше. ~~silly me~~ Наверное только ТМ (каким должен был быть и сам ПР с ксеносами), до момента, как я сделаю на небольшой рефактор на ТГ и он дойдет до нас.
Сам ПР фиксит проблему, что яйца королевы являются обычными и создают таких же обычных ксеносов
Новые ксеносы теперь работают
<details>
Королева создает правильный яйца
Из них вылупляются правильные штуки
Которые создают правильные эмбрионы в теле
И из которых вырастают правильные ларвы
</details>
:cl:
fix: TGMC xenos queen now creates the correct eggs. From which the right facehuggers hatch. And which creates the right embryos in the victims' bodies.
/:cl:
=> Фикс ТГМС-ксеносов

modular_nova/master_files/code/modules/antagonists/changeling/changeling.dm
Убираем модульный оверрайд от новы.
У генокрадов будет чуть больше смысла жизни с нормальными целями.
<details>
</details>
:cl:
fix: fixes changeling antag having no objectives
/:cl:
=> Фикс целей генокрадов

code/__HELPERS/logging/mob.dm
=> [TM-ONLY] Очень важный фикс логов (возможно нерабочий)

tff_modular/modules/antagonism_updates/contractor_gear.dm, tgstation.dme
Контрактник теперь спавнится с тазером, Хайль Синдикат
<details>
</details>
:cl:
add: added Taser to initial contractor loadout
/:cl:
=> Добавляет контрактнику тазер

tff_modular/modules/security-rearm/code/p207.dm, tff_modular/modules/security-rearm/code/p213.dm, tff_modular/modules/security-rearm/code/security_beacon.dm, tgstation.dme
Фикс коробки в маяке, ибо @Bannhammger устроил демилитаризацию
Хотфикс
:cl:
fix: Из-за недобросовестного поставщика чуть не произошла замена всех Гуэпэ в ящиках на кинетические пистолеты. Демилитаризация отменена.
/:cl:
=> FIX DEMILITARISATION

modular_nova/modules/cortical_borer/code/cortical_borer.dm, tff_modular/modules/borer-rebalance/borer_ff.dm, tff_modular/modules/martial/sleeping_carp.dm, tgstation.dme
Бореры теперь получают 0чко раз в 15 минут и имеют реген химикатов 1,5. ура
<details>
</details>
:cl:
balance: borer chem regen increased to 1.5 from 1
balance: borer maturity treshold lowered to 15 
/:cl:
=> Увеличивает скорость взросления cocktical vorer, увеличивает хим реген

config/maps.txt, modular_nova/modules/bitrunning/code/virtual_domains/ancient_milsim/virtual_domain.dm
Убрал карту из битрана, на которой куча убивающих клиенты мешков. ПР НЕ в основную ветку, а в ветку с "фиксом". 
С прошлым ПР-ом немного закосячил
upd
Так же убрана блюшифт из ротации, потому что на этой карте есть эти мешки
=> Одна карта в битране убивает клиенты. Это "фикс"

html/changelogs/AutoChangeLog-pr-4996.yml, html/changelogs/AutoChangeLog-pr-5002.yml, html/changelogs/AutoChangeLog-pr-5029.yml, modular_nova/master_files/code/modules/projectiles/guns/ballistic/rifle.dm, modular_nova/modules/mapping/code/interdyne_mining.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/MainPage.tsx
пара пров. важен лишь фикс краша редактора
=> Nova batch 17-03

tff_modular/master_files/code/game/objects/items/storage/bags.dm, tgstation.dme
Быстрый фикс сумок для сбора - акшен баттон работает теперь в любом слоте
фикс
:cl:
fix: Fixed collect type button of bags.
/:cl:
=> quickfix bags

modular_nova/modules/loadouts/loadout_items/loadout_datum_erp.dm
буквально то же самое что в заголовке пра.
отрубает возможность брать ерп айтемы в лодауте, прощай сб мета на бсдм коробку
:cl:
del: Customs committee has banned all personal enterprise resource planning tools. You can only gain them from proprietary ERP vendor
/:cl:
=> Половина маршрутки плакала: Отключение выбора ЕРП предметов в лодауте

tff_modular/modules/martial/sleeping_carp.dm
карп снова отражает только в режиме броска
<details>
</details>
:cl:
add: eepy seepy carp once again can deflect projectiles only in throw mode
/:cl:
=> карпум нефрум

modular_nova/master_files/code/_globalvars/regexes.dm
Ещё давно попросили для кириллицы автопунктуацию сделать. Вот она.
Точки в конце предложений увеличивают РП на сервере на целых два порядка. Общеизвестный факт.
<details>
</details>
:cl:
fix: autopunctuation now supports cyrillic too
/:cl:
=> Точки в конце фраз для кириллицы

code/modules/mod/mod_activation.dm
Упс, я замерджил коммиты не в том порядке. Ну, бывает. Никто же не страдал от нерабочей защиты от радейки. ДА ВЕДЬ?
=> Фикс защиты от радиации у модов

modular_nova/modules/sec_haul/code/misc/vending.dm, modular_nova/modules/sec_haul/code/security_clothing/armadyne_clothing.dm
Добавляет в секдроб армадайн одежду. Имеет такие же характеристики как и обычная.
Больше одежды для СБ!
<details>
</details>
:cl: Saukykouko
add: Добавлена Армадайн одежда в секдроб.
/:cl:
=> Добавить армадайн одежду в секдроб

tgui/packages/tgui/interfaces/Changelog.jsx
Изменяет название сервера в ченджлоге. Ну и добавляет нову в список благодарности.
Не уверен что тут нужны комментарии (учитывая, что тут их по хорошему и не поставишь). Но если будут нужны - попробую добавить
Так и должно быть
<details>
</details>
:cl:
fix: Changed server name in changelog to Fluffy Frontier
/:cl:
=> Название сервера в ченджлоге

.github/workflows/stale.yml
Я откровенно устал убирать эти фигни у всех ПР-ов. Большая часть из которых висит открытой потому что их некому проверить из других мейнтейнеров
Это поможет мне
Не требуется
=> Повышает время до стейла и удаления ПР-а до 30 дней

_maps/RandomRuins/IceRuins/fluffy/icemoon_interdyne_base_ff.dmm, _maps/RandomRuins/LavaRuins/fluffy/lavaland_interdyne_base_ff.dmm
Не позволяет газу из майнера идти в дистро. То есть никаких 50/50 миксов там. Ещё чинит микс камеру, которая стоит в инженерном. Два инжектора лежат один поверх другого - красиво, но нечитаемо.
Вульпочки, вернитесь на вульподайн, я всё починил
Ой как я заколебался по каждому фиксу сидеть пускать локалку
Это же не кламы даже по объему работы...
На, смотрите, я и правда поменял одну трубу на другую
<details>
</details>
:cl:
map: Makes interdyne a tad better by fixing its atmos
/:cl:
=> Чиним пару спорных инженерных решений дюны

.github/workflows/compile_changelogs.yml
=> CHANGE IN REPO ONLY [TEST]
